openapi: 3.0.3
info:
  title: Fake Store API
  description: Fake store API
  version: 1.0.0
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
servers:
  - url: http://localhost:3000
    description: Development Environment
paths:
  /products:
    parameters:
      - name: product-category
        in: query
        description: Filter by product ID
        required: false
        schema:
          type: string
    get:
      summary: List all products
      operationId: ListProducts
      description: List all products
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productIds
              properties:
                productIds:
                  type: array
                  items:
                    type: integer
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    parameters:
      - name: productId
        in: path
        description: ID of the product
        required: true
        schema:
          type: integer
    get:
      summary: Get product by ID
      operationId: GetProductByID
      description: Get product by ID
      tags:
        - products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  /orders:
    get:
      summary: List all orders
      operationId: ListOrders
      tags:
        - orders
      description: Retrieve all orders. Optionally filter by `order_id` to get a
        specific order.
      parameters:
        - name: order_id
          in: query
          description: Filter by order ID
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      summary: Create an order (max 5 items)
      operationId: CreateOrder
      tags:
        - orders
      description: Creates a new order with the given product IDs. Maximum of 5
        products allowed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productIds
              properties:
                productIds:
                  type: array
                  items:
                    type: integer
      responses:
        "201":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid request
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - category
        - price
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        price:
          type: number
    Order:
      type: object
      required:
        - id
        - productIds
        - status
      properties:
        id:
          type: integer
        productIds:
          type: array
          items:
            type: integer
        status:
          type: string
          enum:
            - active
            - cancelled
tags:
  - name: products
  - name: orders
