extends: spectral:oas

rules:
  query-parameters-snake-case:
    description: Query parameters must be in snake_case
    message: Query parameter "{{property}}" should be in snake_case
    given: "$.paths[*][*].parameters[?(@.in == 'query')].name"
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^[a-z0-9]+(_[a-z0-9]+)*$"
