# .github/workflows/test.yml
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1
      - run: inso --version
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Lint
        run: inso lint spec "swagger.yaml" --ci --workingDir ${{ github.workspace }}
      - name: Run collection
        run: inso run collection wrk_2de023 -e env_2b8c8b --bail --workingDir ${{ github.workspace }}
      - name: Run test suites
        run: inso run test "New Suite" --env specenv --ci --workingDir ${{ github.workspace }}
      - name: Run collection
        run: inso run test "My Collection" --env specenv --ci --workingDir ${{ github.workspace }}
