# .github/workflows/test.yml
name: Run API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Inso CLI v11.2.0
        run: |
          curl -L https://github.com/Kong/insomnia/releases/download/core%4011.2.0/inso-linux-11.2.0.tar.xz --output inso.tar.xz
          mkdir inso
          tar -xf inso.tar.xz -C inso
          sudo mv inso/inso /usr/local/bin/
          inso --version

      - name: Lint OpenAPI Spec
        run: inso lint spec swagger.yaml --ci --workingDir ${{ github.workspace }}

      - name: Run collection by ID
        run: inso run collection wrk_2de023 -e env_2b8c8b --bail --workingDir ${{ github.workspace }}

      - name: Run test suite "New Suite"
        run: inso run test "New Suite" --env specenv --ci --workingDir ${{ github.workspace }}

      - name: Run test suite "My Collection"
        run: inso run test "My Collection" --env specenv --ci --workingDir ${{ github.workspace }}
